export const FETCH_BOOKS_LIST_SUCCESS = "FETCH_BOOKS_LIST_SUCCESS";
export const LOADING = "LOADING";
export const FETCH_BOOK_DATA_FAILURE = "FETCH_BOOK_DATA_FAILURE";
export const FETCH_BOOK_LIST_REQUESTED ="FETCH_BOOK_LIST_REQUESTED";